# UCL, University College London: Myriad + SGE
host_name: "Myriad"
host_login: "myriad.rc.ucl.ac.uk"
host_location: "University College London"
host_homedir: "/home"
host_prompt: "[yourUsername@login12 ~]$ "
local_prompt: "[user@laptop ~]$"
sched_name: "SGE"
sched_submit: "qsub"
sched_submit_options: ""
sched_status: "qstat"
sched_flag_user: "-u yourUsername"
sched_del: "qdel"
sched_interactive: "qrsh"
sched_flag_interactive: "-l mem=512M,h_rt=2:00:00"
sched_info: "qhost"
sched_comment: "#$ "
sched_flag_name: "-N"
sched_hist: "jobhist"
sched_flag_histdetail: "-j"
