# EPCC, The University of Edinburgh: Cirrus + PBS Pro
host_name: "Myriad"
host_login: "myriad.rc.ucl.ac.uk"
host_location: "University College London"
host_homedir: "/home"
host_prompt: "[yourUsername@login12 ~]$ "
local_prompt: "[user@laptop ~]$"
sched_name: "SGE"
sched_submit: "qsub"
sched_submit_options: "-A tc001 -q R387726"
sched_status: "qstat"
sched_flag_user: "-u yourUsername"
sched_del: "qdel"
sched_interactive: "qsub"
sched_flag_interactive: "-IVl select=1:ncpus=1"
sched_info: "pbsnodes -a"
sched_comment: "#SGE"
sched_flag_name: "-N"
sched_hist: "qstat -x"
sched_flag_histdetail: "-f"
